"""Compile the diagnostic HLSL to validated DXIL using an installed DXC.

Supply the official Windows SDK dxc.exe or the official Linux DXC executable.
No compiler, validator, or proprietary runtime binary is redistributed here.
"""
import argparse
import pathlib
import struct
import subprocess
import tempfile


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--dxc', required=True, type=pathlib.Path)
    parser.add_argument('--output', required=True, type=pathlib.Path)
    args = parser.parse_args()
    if args.output.exists():
        parser.error('Use a fresh output path, then review its diff against triangle_shaders.h')
    source = pathlib.Path(__file__).with_name('triangle_shaders.hlsl')
    lines = ['// SPDX-License-Identifier: MIT', '// Generated by compile_triangle_shaders.py from triangle_shaders.hlsl; DXC, shader model 6.0.', '#pragma once']
    with tempfile.TemporaryDirectory(prefix='.triangle-dxil-', dir=args.output.parent.resolve(strict=True)) as temporary:
        for name, entry, profile in (('TriangleVertexShader','VSMain','vs_6_0'), ('TrianglePixelShader','PSMain','ps_6_0')):
            binary = pathlib.Path(temporary) / (entry + '.dxil')
            subprocess.run([str(args.dxc.resolve()), '-T', profile, '-E', entry, '-O3', '-Ges',
                            '-Qstrip_debug', '-Qstrip_reflect', '-Fo', str(binary), str(source)], check=True, timeout=30)
            data = binary.read_bytes()
            if not 32 <= len(data) <= 65536 or data[:4] != b'DXBC' or data[4:20] == bytes(16) or struct.unpack_from('<I', data, 24)[0] != len(data):
                raise ValueError('DXC did not produce a bounded validated shader container')
            offsets = struct.unpack_from('<' + 'I' * struct.unpack_from('<I', data, 28)[0], data, 32)
            if not any(data[offset:offset+4] == b'DXIL' for offset in offsets):
                raise ValueError('The pipeline needs DXIL, not legacy DXBC instructions')
            lines.append(f'static constexpr unsigned char {name}[]{{')
            lines.extend('    ' + ''.join(f'0x{byte:02x},' for byte in data[start:start+16]) for start in range(0,len(data),16))
            lines.append('};')
            print(f'{name}: {len(data)} validated DXIL bytes')
    with args.output.open('x', encoding='utf-8', newline='\n') as output:
        output.write('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
