// SPDX-License-Identifier: MIT
// Local compatibility test. Inputs are generated by this machine's WSL UMD.
// No rendering or submission; all successfully created contexts are destroyed.
#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>
#include <winternl.h>
#include <d3dkmthk.h>
#include <dxgi1_4.h>
#include <wrl/client.h>
#include <cstdio>
#include <cstdint>
#include <cstring>
#include <vector>
using Microsoft::WRL::ComPtr;
struct ContextHeader { std::uint32_t magic, node, engine, flags, clientHint, bytes; };
int main(int argc,char** argv) {
    if(argc!=2 && argc!=3) return 2;
    FILE* file=nullptr;
    if(fopen_s(&file,argv[1],"rb") || !file) return 2;
    ContextHeader input{};
    if(std::fread(&input,1,sizeof input,file)!=sizeof input || input.magic!=0x31585443 ||
       !input.bytes || input.bytes>4096 || input.node>7 || input.engine!=1 ||
       (input.flags!=0 && input.flags!=16) || input.clientHint!=12) { std::fclose(file); return 2; }
    std::vector<unsigned char> payload(input.bytes);
    const bool valid=std::fread(payload.data(),1,payload.size(),file)==payload.size() && std::fgetc(file)==EOF;
    std::fclose(file); if(!valid) return 2;
    std::vector<unsigned char> queuePayload;
    if(argc==3) {
        if(fopen_s(&file,argv[2],"rb") || !file) return 2;
        std::uint32_t header[4]{};
        if(std::fread(header,1,sizeof header,file)!=sizeof header || header[0]!=0x31554551 ||
           header[2]!=0 || header[3]>4096) { std::fclose(file); return 2; }
        queuePayload.resize(header[3]);
        const bool qvalid=std::fread(queuePayload.data(),1,queuePayload.size(),file)==queuePayload.size() && std::fgetc(file)==EOF;
        std::fclose(file); if(!qvalid) return 2;
    }
    ComPtr<IDXGIFactory1> factory;
    if(FAILED(CreateDXGIFactory1(IID_PPV_ARGS(&factory)))) return 1;
    LUID luid{}; bool found=false;
    for(UINT n=0;;++n) {
        ComPtr<IDXGIAdapter1> adapter;
        if(factory->EnumAdapters1(n,&adapter)==DXGI_ERROR_NOT_FOUND) break;
        DXGI_ADAPTER_DESC1 desc{};
        if(!adapter || FAILED(adapter->GetDesc1(&desc))) return 1;
        if(desc.VendorId==0x10de && !(desc.Flags & DXGI_ADAPTER_FLAG_SOFTWARE)) {
            luid=desc.AdapterLuid; found=true;
            std::printf("{\"vendor\":%u,\"device\":%u,",desc.VendorId,desc.DeviceId); break;
        }
    }
    if(!found) return 1;
    D3DKMT_OPENADAPTERFROMLUID adapter{}; adapter.AdapterLuid=luid;
    auto status=D3DKMTOpenAdapterFromLuid(&adapter);
    std::printf("\"openStatus\":\"%08lx\",",static_cast<unsigned long>(status));
    if(status<0) { std::puts("\"success\":false}"); return 1; }
    D3DKMT_CREATEDEVICE device{}; device.hAdapter=adapter.hAdapter;
    const unsigned flags=2; static_assert(sizeof flags==sizeof device.Flags);
    std::memcpy(&device.Flags,&flags,sizeof flags);
    status=D3DKMTCreateDevice(&device);
    std::printf("\"deviceStatus\":\"%08lx\",",static_cast<unsigned long>(status));
    bool ok=status>=0;
    if(ok) {
        D3DKMT_CREATECONTEXTVIRTUAL context{};
        context.hDevice=device.hDevice; context.NodeOrdinal=input.node; context.EngineAffinity=input.engine;
        context.Flags.Value=input.flags; context.ClientHint=static_cast<D3DKMT_CLIENTHINT>(input.clientHint);
        context.PrivateDriverDataSize=input.bytes; context.pPrivateDriverData=payload.data();
        status=D3DKMTCreateContextVirtual(&context);
        std::printf("\"node\":%u,\"contextFlags\":%u,\"privateBytes\":%u,\"contextStatus\":\"%08lx\",",
                    input.node,input.flags,input.bytes,static_cast<unsigned long>(status));
        ok=status>=0;
        if(status>=0) {
            if(argc==3) {
                D3DKMT_CREATEHWQUEUE queue{}; queue.hHwContext=context.hContext;
                queue.PrivateDriverDataSize=static_cast<UINT>(queuePayload.size());
                queue.pPrivateDriverData=queuePayload.empty()?nullptr:queuePayload.data();
                status=D3DKMTCreateHwQueue(&queue); ok=ok && status>=0;
                std::printf("\"queuePrivateBytes\":%u,\"queueStatus\":\"%08lx\",",queue.PrivateDriverDataSize,static_cast<unsigned long>(status));
                if(status>=0) {
                    const bool mapped=queue.HwQueueProgressFenceCPUVirtualAddress && queue.HwQueueProgressFenceGPUVirtualAddress && queue.hHwQueueProgressFence;
                    const auto fence=mapped?*static_cast<volatile UINT64*>(queue.HwQueueProgressFenceCPUVirtualAddress):0;
                    std::printf("\"queueFenceMapped\":%s,\"initialQueueFence\":%llu,",mapped?"true":"false",fence);
                    ok=ok && mapped;
                    D3DKMT_DESTROYHWQUEUE dq{}; dq.hHwQueue=queue.hHwQueue;
                    status=D3DKMTDestroyHwQueue(&dq); ok=ok && status>=0;
                    std::printf("\"destroyQueueStatus\":\"%08lx\",",static_cast<unsigned long>(status));
                }
            }
            D3DKMT_DESTROYCONTEXT destroy{}; destroy.hContext=context.hContext;
            status=D3DKMTDestroyContext(&destroy); ok=ok && status>=0;
            std::printf("\"destroyContextStatus\":\"%08lx\",",static_cast<unsigned long>(status));
        }
        D3DKMT_DESTROYDEVICE destroy{}; destroy.hDevice=device.hDevice;
        status=D3DKMTDestroyDevice(&destroy); ok=ok && status>=0;
        std::printf("\"destroyDeviceStatus\":\"%08lx\",",static_cast<unsigned long>(status));
    }
    D3DKMT_CLOSEADAPTER close{}; close.hAdapter=adapter.hAdapter;
    status=D3DKMTCloseAdapter(&close); ok=ok && status>=0;
    std::printf("\"closeStatus\":\"%08lx\",\"success\":%s}\n",static_cast<unsigned long>(status),ok?"true":"false");
    return ok?0:1;
}
